[tests/abi] make this test work on OpenBSD

diff --git a/tests/abi b/tests/abi
--- a/tests/abi
+++ b/tests/abi
@@ -1,6 +1,15 @@
 #!/bin/sh -e
 
 echo "Library Path: $LIBVERTO" >&2
+echo -n "Hash: "
+if which md5sum 2>/dev/null; then
+  HASHCMD="md5sum"
+elif which md5; then
+  HASHCMD="md5"
+else
+  echo "ERROR!"
+  exit 1
+fi
 
-HASH=`nm -g $LIBVERTO | awk '/^[0-9a-fA-F]+ T / { print $NF; }' | sort -u | md5sum | cut -d' ' -f1`
+HASH=`nm -g $LIBVERTO | awk '/^[0-9a-fA-F]+ T / { print $NF; }' | sort -u | $HASHCMD | cut -d' ' -f1`
 test $HASH == 6910468a2981605ab75fd3c21150e400
